#!/bin/bash
echo Use this only for guide
exit 1

sudo usermod -a -G cmsuser $USER
sudo su - postgres
createuser cmsuser -P
createdb -O cmsuser database
psql database -c 'ALTER SCHEMA public OWNER TO cmsuser'
psql database -c 'GRANT SELECT ON pg_largeobject TO cmsuser'
cmsInitDB


