#!/bin/bash
#usage: exception <ip>
if [ "$#" -eq 1 ]; then
    sudo iptables -A TCP -p tcp -m tcp -s $1 --dport 8890 -j ACCEPT || exit 1
    sudo iptables -A TCP -p tcp -m tcp -s $1 --dport 8637 -j ACCEPT || exit 1
fi
