#!/bin/bash
echo Use this only for guide
exit 1

#Read the docs
# https://cms.readthedocs.org/en/latest/
# https://wiki.archlinux.org/index.php/PostgreSQL

#regenerate localizations
xgettext -o po/cms.pot --language=Python --no-location \
  --keyword=_:1,2 --keyword=N_ --keyword=N_:1,2 --width=79 \
  cms/grading/*.py cms/grading/*/*.py cms/server/*.py \
  cms/server/contest/*.py cms/server/contest/handlers/*.py \
  cms/server/contest/templates/*.html

#install postgres
sudo pacman -U postgresql
sudo -i -u postgres
initdb --locale en_US.UTF-8 -E UTF8 -D '/var/lib/postgres/data'

#postgres config
sudo cp conf/pg_hba.conf conf/postgresql.conf /var/lib/postgres/data/
cp conf/cms.conf conf/cms.ranking.conf /usr/local/etc/

sudo systemctl enable postgresql
sudo systemctl start postgresql

#setup database
sudo su - postgres
createuser cmsuser -P
createdb -O cmsuser database
psql database -c 'ALTER SCHEMA public OWNER TO cmsuser'
psql database -c 'GRANT SELECT ON pg_largeobject TO cmsuser'
sudo usermod -a -G cmsuser $USER

sudo mkdir -p /var/local/cache/cms
sudo mkdir -p /var/local/log/cms
sudo chown oiapoli /var/local/log/cms
sudo mkdir -p /var/local/lib/cms/ranking
sudo chown oiapoli /var/local/lib/cms/ranking
sudo mkdir -p /usr/local/share/locale


#util scripts
sudo ln -sv exception /usr/bin/cmsException
sudo ln -sv load /usr/bin/cmsLoad
sudo ln -sv run /usr/bin/cmsRun

#example: allow port 8890
sudo iptables -A TCP -p tcp -m tcp --dport 8890 -j ACCEPT
