#!/bin/bash
echo Use this only for guide
exit 1

#Read the docs
# https://cms.readthedocs.org/en/latest/
# https://wiki.archlinux.org/index.php/PostgreSQL

#regenerate localizations
xgettext -o po/cms.pot --language=Python --no-location \
  --keyword=_:1,2 --keyword=N_ --keyword=N_:1,2 --width=79 \
  cms/grading/*.py cms/grading/*/*.py cms/server/*.py \
  cms/server/contest/*.py cms/server/contest/handlers/*.py \
  cms/server/contest/templates/*.html

#install postgres
sudo pacman -U postgresql
sudo -i -u postgres
sudo mkdir /var/lib/postgres/data
initdb --locale en_US.UTF-8 -E UTF8 -D '/var/lib/postgres/data'
sudo systemctl enable postgresql
sudo systemctl start postgresql

#postgres config
sudo cp $DIR/conf/pg_hba.conf $DIR/conf/postgresql.conf /var/lib/postgres/data/

#setup database
sudo usermod -a -G cmsuser $USER
sudo su - postgres
createuser cmsuser -P
createdb -O cmsuser database
psql database -c 'ALTER SCHEMA public OWNER TO cmsuser'
psql database -c 'GRANT SELECT ON pg_largeobject TO cmsuser'

