#!/bin/bash
set -x verbose
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#regenerate localizations
xgettext -o cms/server/po/messages.pot --language=Python --no-location \
  --keyword=_:1,2 --keyword=N_ --keyword=N_:1,2 --width=79 \
  cms/grading/*.py cms/grading/*/*.py cms/server/*.py \
  cms/server/templates/admin/*.html \
  cms/server/templates/contest/*.html || exit 1

#build n install
./setup.py build || exit 1
sudo ./setup.py install || exit 1

#postgres
sudo cp $DIR/conf/pg_hba.conf $DIR/conf/postgresql.conf /var/lib/postgres/data/ || exit 1
#cmsconf
cp $DIR/conf/cms.conf $DIR/conf/cms.ranking.conf /usr/local/etc/ || exit 1

#ranking
rm -r /var/local/lib/cms/ranking/*
cp $DIR/ranking/logo.jpg /var/local/lib/cms/ranking/logo.jpg || exit 1
cp -r $DIR/ranking/teams /var/local/lib/cms/ranking/ || exit 1
cp -r $DIR/ranking/flags /var/local/lib/cms/ranking/ || exit 1
