#!/bin/bash
set -x
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#ranking
rm -r /var/local/lib/cms/ranking/* || exit 1
cp $DIR/ranking/logo.jpg /var/local/lib/cms/ranking/logo.jpg || exit 1
cp -r $DIR/ranking/teams /var/local/lib/cms/ranking/ || exit 1
cp -r $DIR/ranking/flags /var/local/lib/cms/ranking/ || exit 1
exit 0

