#!/bin/bash
#https://cms.readthedocs.org/en/latest/
set -x
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
sudo systemctl start postgresql || exit 1
if [ "$#" -ge 1 ]; then
    cmsImporter -d $1 || exit 1
fi
$DIR/reset_ranking || exit 1

sudo systemctl restart iptables || exit 1
if [ "$#" -ge 2 ]; then
    #sudo iptables -D TCP 1 || exit 1 #elimina la regla 1
    sudo iptables -A TCP -p tcp -m tcp -s $2 --dport 8890 -j ACCEPT || exit 1
    sudo iptables -A TCP -p tcp -m tcp -s $2 --dport 8637 -j ACCEPT || exit 1
fi

screen -c $DIR/start_services || exit 1
exit 0


