#!/bin/bash
#https://cms.readthedocs.org/en/latest/
sudo systemctl start postgresql || exit 1
cd ~/cms-oia || exit 1
./util_scripts/reset_ranking || exit 1

sudo systemctl restart iptables || exit 1
if [ "$#" -eq 1 ]; then
    #sudo iptables -D TCP 1 || exit 1 #elimina la regla 1
    sudo iptables -A TCP -p tcp -m tcp -s $1 --dport 8890 -j ACCEPT || exit 1
    sudo iptables -A TCP -p tcp -m tcp -s $1 --dport 8637 -j ACCEPT || exit 1
fi

screen -c ./util_scripts/start_services || exit 1
exit 0


